### ISSUE TITLE
Typo in publishing -> logos and images -> item format images

### ISSUE THREAD

**Issue by rsmithlal** [conferenceplan/planner-core#2]
"Coffe" break chat should be "coffee"
![screen shot 2015-07-22 at 4 06 34 pm](https://cloud.githubusercontent.com/assets/11048570/8835979/dea6b16c-308b-11e5-918a-93d3d3c5e0f2.png)
.

**Comment by balen** [comment]
This is not a code issue. The names of items formats are controlled by the planner and not within the scope of the code.
